### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by SrihariMadhavan** [dso-org/deep-symbolic-optimization#95]
Im Trying to install the library in ubuntu and I get the following error:

  Preparing metadata (setup.py) ... done
Collecting pytest (from dso==1.0.dev0)
  Using cached pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Collecting cython (from dso==1.0.dev0)
  Using cached Cython-3.0.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting numpy<=1.19 (from dso==1.0.dev0)
  Using cached numpy-1.19.0.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "/home/FCAM/smadhavan/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/FCAM/smadhavan/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/FCAM/smadhavan/miniconda3/envs/py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-6kgpuoqr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-6kgpuoqr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-6kgpuoqr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 465, in setup_package
        File "/tmp/pip-install-pvr29wjb/numpy_d7f2775fbb8746b79f35f38c2837a710/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-install-pvr29wjb/numpy_d7f2775fbb8746b79f35f38c2837a710/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-install-pvr29wjb/numpy_d7f2775fbb8746b79f35f38c2837a710/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by SrihariMadhavan** [comment]
Please let me know how to proceed. I followed the instructions and upgraded both setuptools and pip

**Comment by Quantbrinx** [comment]
got same error. any fix or updates on this?

**Comment by Qamar-93** [comment]
Python version should be <=3.7, and it only worked with conda:
This worked for me:
``` conda create --name dso_env python=3.7
    conda activate `dso_env`
    pip install "numpy<=1.19" Cython
```
Then running the ` pip install -e ./dso ` should work.
Note: 
TensorFlow 1.14 requires protobuf version 3.20.x or lower, so you might need to downgrade the protobuf version:
` pip install protobuf==3.20.* `

**Comment by 1ArgoS1** [comment]
Adding over @Qamar-93, This error is happening because NumPy 1.19 (which is required by dso) relies on legacy distutils APIs that are no longer provided by newer versions of setuptools. A common workaround is to downgrade setuptools to a version that still supports the expected APIs . I have tested python 3.10, 3.9, 3.8, and 3.7 and  version 3.7 or below  are compatible with tensorflow and numpy.  Thus one should **install python 3.7** as :  
```bash
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.7 python3.7-venv python3.7-dev
```
Then activate the virtual environment ( mandatory in latest ubuntu versions) :
```bash
python3.7 -m venv myenv37
source myenv37/bin/activate
```
Versions of dependency(try to match these):
``` 
protobuf==3.20.3
tensorflow=1.14.0
numpy=1.14.0
setuptools=47.1.0
wheel=0.42.0
pip=23.0.1
```
Then finally run the script : 
```
pip install -e ./dso
```

**Comment by gusis626** [comment]
> Adding over [@Qamar-93](https://github.com/Qamar-93), This error is happening because NumPy 1.19 (which is required by dso) relies on legacy distutils APIs that are no longer provided by newer versions of setuptools. A common workaround is to downgrade setuptools to a version that still supports the expected APIs . I have tested python 3.10, 3.9, 3.8, and 3.7 and version 3.7 or below are compatible with tensorflow and numpy. Thus one should **install python 3.7** as :
> 
> sudo apt install software-properties-common
> sudo add-apt-repository ppa:deadsnakes/ppa
> sudo apt update
> sudo apt install python3.7 python3.7-venv python3.7-dev
> 
> Then activate the virtual environment ( mandatory in latest ubuntu versions) :
> 
> python3.7 -m venv myenv37
> source myenv37/bin/activate
> 
> Versions of dependency(try to match these):
> 
> ```
> protobuf==3.20.3
> tensorflow=1.14.0
> numpy=1.14.0
> setuptools=47.1.0
> wheel=0.42.0
> pip=23.0.1
> ```
> 
> Then finally run the script :
> 
> ```
> pip install -e ./dso
> ```

Hi, thanks for your instructions, I followed them and run the config/examples/control/Hopper.json file, and it display this, is this correct?



(myenv37) (base) gusis@gusis-VirtualBox:~/Desktop/DSOO$ python -m dso.run dso/dso/config/examples/control/Hopper.json

== EXPERIMENT SETUP START ===========
Task type            : control
Environment          : HopperBulletEnv-v0
Starting seed        : 0
Runs                 : 1
== EXPERIMENT SETUP END =============

== TRAINING SEED 0 START ============
pybullet build time: Jun  2 2020 06:48:23
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loading a model without an environment, this model cannot be trained until it has a valid environment.
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
-- BUILDING PRIOR START -------------
WARNING: Skipping invalid 'RelationalConstraint' with arguments {'targets': [], 'effectors': [], 'relationship': None}. Reason: Prior disabled.
WARNING: Skipping invalid 'RepeatConstraint' with arguments {'tokens': 'const', 'min_': None, 'max_': 3}. Reason: Prior disabled.
WARNING: Skipping invalid 'ConstConstraint' with arguments {}. Reason: Uses Tokens not in the Library.
WARNING: Skipping invalid 'DomainRangeConstraint' with arguments {}. Reason: Prior disabled.
WARNING: Skipping invalid 'LanguageModelPrior' with arguments {'weight': None}. Reason: Prior disabled.
WARNING: Skipping invalid 'MultiDiscreteConstraint' with arguments {'dense': False, 'ordered': False}. Reason: Prior disabled.
LengthConstraint: Sequences have minimum length 4.
                  Sequences have maximum length 30.
RelationalConstraint: [exp] cannot be a child of [log].
InverseUnaryConstraint: RelationalConstraint: [log] cannot be a child of [exp].
TrigConstraint: [sin, cos] cannot be a descendant of [sin, cos].
NoInputsConstraint: Sequences contain at least one input variable Token.
UniformArityPrior: Activated.
SoftLengthPrior: No description available.
-- BUILDING PRIOR END ---------------

WARNING: max_length (64) will be overridden by value from LengthConstraint (30).
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
Loaded TD3 model /home/gusis/Desktop/DSOO/dso/dso/task/control/data/HopperBulletEnv-v0/model-td3.pkl
-- RUNNING ITERATIONS START -------------
[00:00:00:46.70] Training iteration 1, current best R: 0.7833

	** New best
	Reward: 0.7833250690497854
	Count Off-policy: 0
	Count On-policy: 1
	Originally on Policy: True
	Invalid: True
	Traversal: log,log,add,div,sin,mul,sub,sub,x3,exp,x6,sub,x8,add,x2,x6,x16,x5,x2
	Expression:
	     ⎛   ⎛        ⎛    ⎛                     x₆⎞⎞⎞⎞
	     ⎜   ⎜     sin⎝x₁₆⋅⎝x₂ + x₃ + x₆ - x₈ - ℯ  ⎠⎠⎟⎟
	  log⎜log⎜x₂ + ──────────────────────────────────⎟⎟
	     ⎝   ⎝                     x₅                ⎠⎠

-- RUNNING ITERATIONS START -------------
-- RUNNING ITERATIONS START -------------
-- RUNNING ITERATIONS START -------------
-- RUNNING ITERATIONS START -------------
-- RUNNING ITERATIONS START -------------
